source "https://rubygems.org"

gem 'nanoc',        '3.6.4'
gem 'adsf',         '1.1.1'
gem 'fssm',         '0.2.10'
gem 'kramdown',     '1.1.0'
gem 'coderay',      '1.0.9'
gem 'pygments.rb',  '0.5.2'
gem 'nokogiri',     '1.6.1'
gem 'rack',         '1.5.2'
gem 'colored',      '1.2'
gem 'cri',          '2.3.0'
gem 'posix-spawn',  '0.3.6'
gem 'yajl-ruby',    '1.1.0'
gem 'listen',       '1.2.2'
gem 'guard-nanoc',  '1.0.1'
gem 'rb-readline'
